import type { Metadata } from "next";
import { Sora, Schoolbell, Baloo_2 } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const sora = Sora({
  variable: "--font-sora",
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const baloo_2 = Baloo_2({
  variable: "--font-baloo-2",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const schoolbell = Schoolbell({
  variable: "--font-schoolbell",
  weight: ['400'],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Asterisco - Agência feita para te destacar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${sora.variable} ${schoolbell.variable} ${baloo_2.variable} antialiased bg-brand-dark`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
